language: cpp

compiler:
  - gcc
  - clang

install:
  # set gcc-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # install boost
  - wget --no-verbose --output-document=boost-trunk.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost-trunk"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost-trunk.tar.bz2 --strip-components=1 -C $BOOST_ROOT
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=iostreams,log)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install)
  # install coveralls
  - sudo pip install cpp-coveralls

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang

before_script:
  - mkdir build
  - cd build
  - if [ "$CXX" = "g++-4.8" ]; then cmake -DBOOST_ROOT=$BOOST_ROOT -DGCOV=ON ..; fi
  - if [ "$CXX" = "clang++" ]; then cmake -DBOOST_ROOT=$BOOST_ROOT ..; fi

script:
  - make
  - ./test_hanal --rsc-dir=../rsc

after_success:
  - cd ..
  - if [ "$CXX" = "g++-4.8" ]; then coveralls --gcov gcov-4.8 --exclude src/test --exclude build; fi
